### ISSUE TITLE
Graphing fails if a node tree doesn't already exist

### ISSUE THREAD

**Issue by Alexey-Ost** [RayMairlot/Scene-Nodes#1]
2.80

Traceback (most recent call last):
  File "/home/sairax/.config/blender/2.80/scripts/addons/sceneNodes.py", line 48, in execute
    nodeGroup = bpy.data.node_groups['NodeTree']
KeyError: 'bpy_prop_collection[key]: key "NodeTree" not found'

location: <unknown location>:-1

2.79

Traceback (most recent call last):
  File "/home/sairax/.config/blender/2.79/scripts/addons/sceneNodes.py", line 48, in execute
    nodeGroup = bpy.data.node_groups['NodeTree']
KeyError: 'bpy_prop_collection[key]: key "NodeTree" not found'

location: <unknown location>:-1

linux mint

**Comment by RayMairlot** [comment]
I don't really do any work on this project now (and I'm unlikely to), but thanks for the report (though in future, please do say what steps to take to reproduce the error, even if it seems incredibly simple).

As a workaround you can click the 'New' button to create a new node tree before pressing 'Graph Scene'.
